### ISSUE TITLE
How to use `hl2sb`'s lua in non-hl2sb projects

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [Planimeter/hl2sb-src#14]

**Comment by andrewmcwatters** [comment]
We never wrote a guide for this. You could do it but you're better off forking hl2sb as a base. That approach would be similar to starting with source-sdk-2006/2007/2013 as a base.

Most of Half-Life 2: Sandbox, as a game and not a mod, is actually in the Lua files themselves. We add support for multi-player in single-player maps, but outside of the addition of Lua, content mounting, and multiplayer support, we don't do anything else besides fix bugs.

If you wanted to take Lua integration directly out of `hl2sb` and add it to an existing mod, you'd need `luamanager.cpp/.h` and all of the related `l*.cpp/h` files which bind their parent files. Such as `lbaseentity.cpp`, etc.

Doing that is sufficient to use Team Sandbox's Lua integration in other Source Engine 1 games.

**Comment by GuestSneezeOSDev** [comment]
Thank you

**Comment by GuestSneezeOSDev** [comment]
@andrewmcwatters could I get a list of files?
